package ephyra.domain.manga.model

import eu.kanade.tachiyomi.source.model.UpdateStrategy

data class MangaUpdate(
    val id: Long,
    val source: Long? = null,
    val favorite: Boolean? = null,
    val lastUpdate: Long? = null,
    val nextUpdate: Long? = null,
    val fetchInterval: Int? = null,
    val dateAdded: Long? = null,
    val viewerFlags: Long? = null,
    val chapterFlags: Long? = null,
    val coverLastModified: Long? = null,
    val url: String? = null,
    val title: String? = null,
    val artist: String? = null,
    val author: String? = null,
    val description: String? = null,
    val genre: List<String>? = null,
    val status: Long? = null,
    val thumbnailUrl: String? = null,
    val updateStrategy: UpdateStrategy? = null,
    val initialized: Boolean? = null,
    val version: Long? = null,
    val notes: String? = null,
    val metadataSource: Long? = null,
    val metadataUrl: String? = null,
    val canonicalId: String? = null,
    val sourceStatus: Int? = null,
    val alternativeTitles: List<String>? = null,
    val deadSince: Long? = null,
    val contentType: ContentType? = null,
    val lockedFields: Long? = null,
)

fun Manga.toMangaUpdate(): MangaUpdate {
    return MangaUpdate(
        id = id,
        source = source,
        favorite = favorite,
        lastUpdate = lastUpdate,
        nextUpdate = nextUpdate,
        fetchInterval = fetchInterval,
        dateAdded = dateAdded,
        viewerFlags = viewerFlags,
        chapterFlags = chapterFlags,
        coverLastModified = coverLastModified,
        url = url,
        title = title,
        artist = artist,
        author = author,
        description = description,
        genre = genre,
        status = status,
        thumbnailUrl = thumbnailUrl,
        updateStrategy = updateStrategy,
        initialized = initialized,
        version = version,
        notes = notes,
        metadataSource = metadataSource,
        metadataUrl = metadataUrl,
        canonicalId = canonicalId,
        sourceStatus = sourceStatus,
        alternativeTitles = alternativeTitles,
        deadSince = deadSince,
        contentType = contentType,
        lockedFields = lockedFields,
    )
}
